### ISSUE TITLE
Changes to combined Report section

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#235]
Combined ticket for a number of changes to the combined Report.  Some details will be tracked in separate documentation.

Content issues
- [x] Add Introduction section.  Read the NCR report intro for motivation and guidance, see additional documentation. https://github.com/ua-snap/arctic-eds/issues/236
- [x] Add Elevation, Geology, Ecoregion to introduction as inline text (with links out to the best online resource for Ecoregion classifications + the USGS Geology map).  Read the NCR report intro for motivation for how to do this. https://github.com/ua-snap/arctic-eds/issues/237
- [x] Remove Geology, Ecoregion sections from report https://github.com/ua-snap/arctic-eds/issues/238
- [x] Combine/deduplicate instances of intro/explainer text that is currently duplicated across sections https://github.com/ua-snap/arctic-eds/issues/240
- [x] Add category headers https://github.com/ua-snap/arctic-eds/issues/241
- [x] Add table of contents (remove link decorations in print view, at least) https://github.com/ua-snap/arctic-eds/issues/242
- [x] Remove multiple instances of including Placename in the report, i.e. just list that at the start. https://github.com/ua-snap/arctic-eds/issues/244
- [x] Add direct link to URL to the introduction section, i.e. "Link to this report: `http://dev.arcticeds.org/report/community/AK124`" https://github.com/ua-snap/arctic-eds/issues/245
- [x] Remove all "Science 101" information completely from the table introductions (see additional documentation for where we want to get). https://github.com/ua-snap/arctic-eds/issues/246
- [x] Where'd Freezing Index and Thawing Index result tables go? https://github.com/ua-snap/data-api/issues/235

Print view issues
- [x] Units in tables are too light when printed to PDF?  (MacOS / Safari) https://github.com/ua-snap/arctic-eds/issues/249
- [x] Buttons should be hidden in print view https://github.com/ua-snap/arctic-eds/issues/250
- [x] Unit switcher should be hidden in print view https://github.com/ua-snap/arctic-eds/issues/251
- [x] Remove HeaderBanner in print mode https://github.com/ua-snap/arctic-eds/issues/252
- [x] Improve print view of LogoBrandHeader (the logo + h1/h2 title/tagline). https://github.com/ua-snap/arctic-eds/issues/253
- [x] Remove links to data from each section https://github.com/ua-snap/arctic-eds/issues/254
- [x] Remove Download CSV buttons from every section https://github.com/ua-snap/arctic-eds/issues/255

**Comment by BobTorgerson** [comment]
We are very close to having this ticket finished! Wrapping up the text in the introductory text and text throughout the report needs to be finalized, but most other functionality is finished.

**Comment by brucecrevensten** [comment]
Done!
